name: My GitHub Action

on: 
  push:
    branches:
      - main  

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: 23f2000762@ds.study.iitm.ac.in  # Your email as the step name
        run: echo "Hello, world!"
